version: '3.7'
services:
  lsms-nginx:
    image: nginx:latest
    container_name: lsms-nginx
    depends_on:
      - lsms-develop
    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
  lsms-develop:
    build:
      context: .docker
      dockerfile: develop/Dockerfile
    container_name: lsms-develop
    environment:
      - CONTAINER_NAME=lsms-develop
      - TZ=Europe/Berlin
      - PHP_IDE_CONFIG=serverName=lsms-develop
      - XDEBUG_CONFIG=idekey=PHPSTORM
      - COMPOSER_ALLOW_SUPERUSER=1
      - COMPOSER=composer-develop.json
    expose:
      - 80
    volumes:
      - .:/var/www
  lsms-mysql:
    image: mysql
    container_name: lsms-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Europe/Berlin
    ports:
      - 3306:3306
    volumes:
      - lsms-mysqldata:/var/lib/mysql
      - .docker/mysql/db-initialization:/docker-entrypoint-initdb.d
volumes:
  lsms-mysqldata:
    driver: local
