version: '3.7'
services:
  lsms-nginx:
    image: nginx:latest
    container_name: lsms-nginx
    depends_on:
      - lsms-develop
      - lsms-swagger-editor
      - lsms-swagger-ui
    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
  lsms-develop:
    build:
      context: .docker
      dockerfile: develop/Dockerfile
    container_name: lsms-develop
    environment:
      - CONTAINER_NAME=lsms-develop
      - TZ=Europe/Berlin
      - PHP_IDE_CONFIG=serverName=lsms-develop
      - XDEBUG_CONFIG=idekey=PHPSTORM
      - COMPOSER_ALLOW_SUPERUSER=1
      - COMPOSER=composer-develop.json
    expose:
      - 80
    volumes:
      - .:/var/www
      - ./config:/var/www/public/api
      - ./../lsms-base:/opt/lsms-base
  lsms-production:
    build:
      context: .docker
      dockerfile: production/Dockerfile
    container_name: lsms-production
    environment:
      - CONTAINER_NAME=lsms-production
      - TZ=Europe/Berlin
      - COMPOSER_ALLOW_SUPERUSER=1
      - COMPOSER=composer-production.json
    expose:
      - 80
    volumes:
      - .:/var/www
      - lsms-productionvendor:/var/www/vendor
      - ./.docker/production/apache2-conf:/etc/apache2/from-host
  lsms-php-fpm:
    build: .docker/php-fpm
    container_name: lsms-php-fpm
    environment:
      - CONTAINER_NAME=lsms-production
      - LSHOP_MS_CONFIGURATION_FILE_NAME=openapi-production
      - TZ=Europe/Berlin
    volumes:
      - .:/var/www
      - lsms-productionvendor:/var/www/vendor
  lsms-mysql:
    image: mysql
    container_name: lsms-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Europe/Berlin
    ports:
      - 3306:3306
    volumes:
      - lsms-mysqldata:/var/lib/mysql
      - .docker/mysql/db-initialization:/docker-entrypoint-initdb.d
  lsms-swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: lsms-swagger-ui
    environment:
      - TZ=Europe/Berlin
    expose:
      - 8080
  lsms-swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: lsms-swagger-editor
    environment:
      - TZ=Europe/Berlin
    expose:
      - 8080
volumes:
  lsms-elasticsearchdata1:
    driver: local
  lsms-elasticsearchdata2:
    driver: local
  lsms-mysqldata:
    driver: local
  lsms-productionvendor:
    driver: local
