version: '3.7'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - web
    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
  web:
    build:
      context: .docker
      dockerfile: develop/Dockerfile
    container_name: web
    environment:
      - CONTAINER_NAME=web
      - TZ=Europe/Berlin
      - PHP_IDE_CONFIG=serverName=web
      - XDEBUG_CONFIG=idekey=PHPSTORM
    expose:
      - 80
    volumes:
      - .:/var/www
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Europe/Berlin
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql
      - .docker/mysql/db-initialization:/docker-entrypoint-initdb.d
volumes:
  mysqldata:
    driver: local
